### ISSUE TITLE
doesnt decode secret file

### ISSUE THREAD

**Issue by kevupton** [futuresimple/helm-secrets#124]
I have a secret file, that is my dockerconfigjson for a private repository. 
I am able to encode this json string no worries, and then decode it no worries manually.

However passing it into comand:
```
helm template . -f docker.secrets.yaml > template.yaml
```

I look at the output and it is the same encoded value.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
#  uid: 51a2d001-9b41-11e9-b591-0800274eb36e
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.docker_auth_secret | b64enc | quote }}
```

when this is compiled. the b64enc is equal to the encoded value.
`ENC[AES256_GCM,data:....]`
