### ISSUE TITLE
Feature request: Read secrets from an azure key vault

### ISSUE THREAD

**Issue by CodingSpiderFox** [futuresimple/helm-secrets#79]
I'd like to retrieve my secrets from an Azure Key Vault

**Comment by claytondus** [comment]
sops version needs to be bumped, support was added in 3.1.0, latest is 3.2.0.

**Comment by svparijs** [comment]
Is this still on going? I was trying this: https://github.com/mozilla/sops#encrypting-using-azure-key-vault

Made a `.sops.yaml`:
```
creation_rules:
  - azure_kv: <redacted>
```

My secrets.yaml version says:

```
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-08-20T07:26:08Z'
    ...
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.3.1
```

Decryption does not work for me:

```
helm secrets dec  promitor-helm/secrets.yaml
Decrypting promitor-helm/secrets.yaml
No keys found in file
Error: plugin "secrets" exited with error
```
Would be really create if this would work!
